# Password
password: p@ssw0rd

server:
  applicationConnectors:
    - type: http
      port: 8080
#    - type: https
#      port: 8443
#      keyStorePath: dropbookmarks.keystore
#      keyStorePassword: p@ssw0rd
#      validateCerts: false

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: punitdh
  #password: 1
  url: jdbc:mysql://localhost:3306/DropBookmarks